name: PHP GrumPhp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  GrumPhp:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run grumphp
        run: /vendor/bin/grumphp run
